### ISSUE TITLE
Enhance Mesh Lens Correction tests

### ISSUE THREAD

**Issue by RussTorres** [AllenInstitute/asap-modules#119]
Add point-cloud mesh lens correction tests and general quality of life improvements as in #118

**Comment by fcollman** [comment]
do we think this is closed now?

**Comment by RussTorres** [comment]
I don't  think the comparison of the resulting transform to the expected has been addressed.  If we still think it should be we should leave this open.

**Comment by RussTorres** [comment]
the transformation part of this has been moved to em_stitch (https://github.com/AllenInstitute/em_stitch), and this level of integration testing seems unnecessary now.  Closing.
