### ISSUE TITLE
Workflow progress guide

### ISSUE THREAD

**Issue by martinschorb** [AllenInstitute/asap-modules#232]
Dear all,

we are using this module as a basis to build alignment and registration work flows for volume SEM data.

What we succeeded in so far:

- conversion of acquisition metadata to render
- stack and mipmap creation
- create tile pairs
- creation of SIFT point matches (despite some [problems](https://github.com/saalfeldlab/render/issues/107) with the client script and spark)

Now, I am stuck in what to do next. Do you, by any chance, have a chart or protocol of what step/tool to use when? Maybe it is part of the module's doc, but I could not find it...

At this point, I am looking for the tool to apply the SIFT-based alignment to each montage slice. I checked [pairwise_rigid_rough.py](https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/rough_align/pairwise_rigid_rough.py), but this seems to expect matching tile pairs across slices, which I don't have yet. Is there another module for this? Or would these be created by the SIFT point match routines, and something went wrong there?

Is there a good tool to explore the point match collection(s) to check where things have worked or gone wrong?

Thanks!

**Comment by martinschorb** [comment]
Or do I dump this into https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/solver/solve.py already?

**Comment by RussTorres** [comment]
> Or do I dump this into https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/solver/solve.py already?

Yes, solving with BigFeta is what you want.

We have started more formally documenting this, but it probably won't make it to this repo in the immediate future.
As you've pieced together, a montage workflow using this repo goes something like this:
Generate Tilespecs -> MIPmap & Apply -> Tilepair -> Pointmatch -> Solve system -> [QC montage](https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/em_montage_qc/detect_montage_defects.py)

The montage qc module tries to identify some common issues like seams (based on pointmatch residuals) and gaps (based on tile overlap)
BigFeta itself actually has some QC tools that can be useful for examining e.g. the density of pointmatches and properties of transformations.
(see https://github.com/AllenInstitute/BigFeta/tree/master/bigfeta/qctools )

Once you have a montage the way we've been doing rough alignment is:
[Make MontageScape (downsampled section)](https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/dataimport/make_montage_scapes_stack.py) -> Tilepair downsampled stack -> Pointmatch -> Solve -> [QC rough](https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/em_montage_qc/rough_align_qc.py) -> [Apply Rough Transforms](https://github.com/AllenInstitute/render-modules/blob/master/rendermodules/rough_align/apply_rough_alignment_to_montages.py)

There are a number of strategies for fine alignment which can vary based on available compute and required precision.  We don't have anything specifically for that in this repo, but in a pinch a strategy very similar to "rough" alignment can provide a decent nonlinear 3d solve while preserving montage quality.

Hope this helps!

**Comment by martinschorb** [comment]
Great, thanks,

I tried to run the solver and get a 
```

ServerSelectionTimeoutError: pc-emcf-16:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 5f7ddcc8ef8a685c230c9f17, topology_type: Single, servers: [<ServerDescription ('pc-emcf-16', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('pc-emcf-16:27017: [Errno 111] Connection refused')>]>

```

Do I need to especially configure the MongoDB instance?
For the rest of the render interactions it does not seem to be necessary to communicate ofer network...

**Comment by martinschorb** [comment]
OK, I managed to enable network access in the MongoDB config

**Comment by RussTorres** [comment]
Bigfeta has an option that allows you to read documents directly from mongodb rather than through the render webservice.  This has been more of a special use case for us, but it is handy when working with e.g. very large collections where json encoding/decoding can cause unwanted latency or for very busy servers (that are not scaled adequately).
Setting the "db_interface" field to "render" in the input/output collection specifications can make this go through render-ws, which better matches the rest of the workflow.
https://github.com/AllenInstitute/BigFeta/blob/e99362060d6ac488eb8c950a24e54d6646942c88/bigfeta/schemas.py#L54
