### ISSUE TITLE
Dockerized execution of some modules results in odd tilespec errors

### ISSUE THREAD

**Issue by fcollman** [AllenInstitute/asap-modules#78]
from a recent test of rough_align..

```
build	04-Feb-2018 11:21:41	ERROR:renderapi.tilespec:Expecting property name enclosed in double quotes: line 1 column 8715 (char 8714)
build	04-Feb-2018 11:21:41	ERROR:renderapi.tilespec:[{"tileId":"20170502194446656_295434_5LC_0064_01_001020_0_45_53.1020.0","layout":
```
it then prints out the json it errored on...

and there is this in there

```
{"imageUrl":"file:/allen/aibs/pipeline/image_processing/volume_assembly/em_modules_test_data/ro4532 2.0989792 3.0803208 -0.68295217 4.2374687 5.063299 16.786694 18.229206 1678.6635 1822.9161 3918283.2 3061562.8 4439767.0 10607175000.0 7118418000.0 7481906700.0 12280997000.0 31254578000000.0 19200693000000.0 17384451000000.0 20756046000000.0 36549404000000.0 9.721539E+16 5.6426443E+16 4.6851715E+16 4.822561E+16 6.189499E+16 1.1407748E+17 100.0 1049.0006 1056.7753 3987740.0 2830459.8 4103453.8 14182161000.0 9325468000.0 9371913000.0 14739135000.0 50239696000000.0 31782357000000.0 28919739000000.0 31928974000000.0 52530596000000.0 1.7867559E+17 1.1062308E+17 9.6105185E+16 9.569362E+16 1.10907996E+17 1.8781408E+17 0.0 3840 3840 "},
```

which looks like the imageUrl and the dataString somehow got corrupted... not sure where/how this is happening ,but gayathri has seen it on other modules too.  Seems related to parallelization.  Could be a render-python issue.

**Comment by fcollman** [comment]
This might be fixed by explicitly initializing a requests session and passing it to render python methods, particularly inside parallel execution with many calls per worker.

**Comment by fcollman** [comment]
this seems to be confirmed to be fixed by controlling the session... not sure we understand why, so leaving this open for now.

**Comment by RussTorres** [comment]
Calling this a won't fix since we've made it to 2023 and processed a few large datasets.
